Второе домашнее задание ч1
htmlacademy-htmlcss/1800797-sedona-31 pull request #2
Opened 2021-06-17 13:57 UTC by Kirill-meta

2021-06-20 18:18 UTC, mikhin requested changes

2021-06-20 18:18 UTC, mikhin commented on index.html
> +    <img src="https://via.placeholder.com/138x70" alt=Логотип Седона">
Пропущена открывающая кавычка после атрибута alt

2021-06-20 18:18 UTC, mikhin commented on index.html
> +</nav>
Здесь нужно сделать правильные отступы, чтобы документ читался легче. Это должен уметь делать твой редактор кода в автоматическом режиме =) Погугли пожалуйста как это сделать. Если не получится, то напиши, и давай разберемся вместе)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +<h1> Седона </h1>
Пробелы после открывающего и перед закрывающим тегом не нужны)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +
Лишняя строка

2021-06-20 18:18 UTC, mikhin commented on index.html
> +  to the gorgeous<br>
Давай пока уберем все br. Посмотрим на этапе CSS, пригодятся ли они нам)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +<section><h2> Welcome</h2>
Давай заголовок перенесем на новую строку, вместе с тегами и уберем лишний пробел)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +  <p> ''Because the Grand <br>
Кавычки не нужно набирать отдельными символами, такой символ есть прям на клавиатуре, вот он — "

2021-06-20 18:18 UTC, mikhin commented on index.html
> +    Canyon sucks!,, </p>
Кавычки не нужно набирать отдельными символами, такой символ есть прям на клавиатуре, вот он — "

2021-06-20 18:18 UTC, mikhin commented on index.html
> +  <p> Седона — небольшой городок в Аризоне, заслуживающий большего! </p>
Все пробелы после открывающего тега нужно убрать во ВСЕМ документе =) Исправишь?)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +
Лишняя строка)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +  <li><h3>Настоящий
Странно, что получился список из одного пункта. Точно так и должно быть?)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +  <li><h3>Настоящий
Тут сейчас слиплись несколько тегов в одну строку. Давай во всем документе сделаем древовидную структуру вложенности?

Типа такого:

![image](https://user-images.githubusercontent.com/38258318/122684204-bc911f80-d20c-11eb-9513-75195e89b93a.png)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +<section> <h2>Приемущества</h2>
Опечатка в слове

2021-06-20 18:18 UTC, mikhin commented on index.html
> +  <a href ="#"><h3>Жилье<h3></a>
Знак `=` должен идти сразу после атрибута, без пробела)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +    <ol start="2">
А зачем start=2 нужен?

2021-06-20 18:18 UTC, mikhin commented on index.html
> +      <li><h3>Там есть Мост дьявола</h3>
Опечатка, пробел пропущен

2021-06-20 18:18 UTC, mikhin commented on index.html
> +находятся очень близко</p> </li>
Тут все как-то слиплось, надо сделать красивое форматирование =)

2021-06-20 18:18 UTC, mikhin commented on index.html
> +     <a href ="#"> <p> Поиск Гостиницы в седоне </p> </a>
Абзац внутри ссылки не нужен, текст может просто лежать в ссылке

2021-06-23 09:24 UTC, mikhin requested changes

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <p> WELCOME to the gorgeous SEDONA</p>
Потому что эту часть можно экспортировать как изображение из Фигмы. Кстати так верстать будет легче)

2021-06-23 09:24 UTC, mikhin commented on index.html
> +
Давай уберем лишние пустые строки во всем файле?

2021-06-23 09:24 UTC, mikhin commented on index.html
> +  <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>
Этот абзац нужен?

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <h2>5 причин - 1</h2>
Заголовок непонятный

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <h3>Настоящий городок</h3>
Может это и будет настоящим заголовком секции? Необязательно всегда делать скрытые заголовки

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <a href="#"><h3>Жилье</h3></a>
Вроде бы это не ссылки, а просто подзаголовки

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <h2>5 причин 2-5</h2>
Заголовок непонятный 2

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <ul>
Непонятно почему первые секции были сделаны section, а тут ul? Вроде бы у них одинаковый дизайн и одинаковый контент? Давай сделаем как-то единообразно?

2021-06-23 09:24 UTC, mikhin commented on index.html
> +        <h3>небольшая площадь</h3>
С большой буквы нужно, как по правилам)

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <a href="#"> Поиск Гостиницы в седоне </a>
А тут же еще форму надо разметить? Вероятно она скрыта как слой в Фигме

2021-06-23 09:24 UTC, mikhin commented on index.html
> +  <section>
Section — тег, имеющий сильное семантическое значение: конкретно, это тег, показывающий что среди всего полезного контента, который есть на сайте, и за которым пользователь специально пришел (а пользователи идут на сайт как правило за контентом, а не за интерфейсом), тут прям находится целый РАЗДЕЛ этого полезного контента.

Из этого следует что тег section нельзя использовать всюду подряд чисто чтобы разделять какие-то куски интерфейса на секции.

В данном случае можно использовать div, т.к. у него нет какого-то особого семантического значения, это просто DIVider — разделитель.

ну и на будещее — не нужно бояться использовать div'ы)

2021-06-23 09:24 UTC, mikhin commented on index.html
> +    <h2>Телефон и хештег</h2>
Такие заголовки не нужны, они не несут пользу)

2021-06-23 10:38 UTC, Kirill-meta commented on index.html
> +  <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>
Он изначально был в intex.html, предположил, что лучше его пока не трогать.

2021-06-23 10:55 UTC, Kirill-meta commented on index.html
> +
Хорошо, я когда изучал в разделе демки 2.17. Барбершоп. Разметка главной страницы, там оставляют такие пустыt строки между <Мейн> и <аш1>. Получается пустых строк не должно быть нигде?

2021-06-23 10:58 UTC, Kirill-meta commented on index.html
> +    <p> WELCOME to the gorgeous SEDONA</p>
Я к сожалению видимо либо пропустил в лайве и в тренажерах такой прием либо его еще не было. А как это сделать? или это пока на потом?

2021-06-23 11:33 UTC, Kirill-meta commented on index.html
> +    <ul>
Я просто не совсем понимаю глядя на макет в фигме. Вначале идёт №1 Настоящий городок. Потом идёт как-будто разделение и другая секция: Жилье, еда, сувениры. И дальше продолжение секции Настоящий городок и пункты 2,3,4,5. Получается разрыва секции Настоящий городок нету и пункты Жилье Еда Сувениры являются лишь частью первой секции?

2021-06-23 11:33 UTC, Kirill-meta commented on index.html
> +        <h3>небольшая площадь</h3>
ок)

2021-06-23 11:51 UTC, Kirill-meta commented on index.html
> +    <a href="#"> Поиск Гостиницы в седоне </a>
"Не нужно размечать содержимое всплывающего окна (попап) с картой, который отрисован в скрытых слоях в макете. Вы завершите вёрстку попапа с картой позже." - это в задании прописано, или это относится к другому popup ?

2021-06-23 11:57 UTC, Kirill-meta commented on index.html
> +  <section>
Понял спасибо)

2021-06-23 13:36 UTC, Kirill-meta commented on index.html
> +    <ul>
<section>
    <h2>Настоящий городок</h2>
    <ul>
      <li>
        <h3>Настоящий городок</h3>
        <p> — №1 —</p>
        <p>Седона — не аттракцион для туристов, там течёт своя жизнь</p>
        <img src="https://via.placeholder.com/800x256" alt="Настоящий городок">
        <h3>Жилье</h3>
        <p>Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
        <h3>Еда</h3>
        <p>Всегда заказывайте фирменный бургер, вы не разочаруетесь!</p>
        <h3>Сувениры</h3>
        <p>Не только китайского, но и местного производства!!</p>
      </li>
      <li>
        <h3>Там есть Мост дьявола</h3>
        <p> — №2 —</p>
        <p>Да,по нему можно пройти! Если конечно вы осмелитесь</p>
        <img src="https://via.placeholder.com/800x256" alt="Настоящий городок">
      </li>
      <li>
        <h3>Небольшая площадь</h3>
        <p> — №3 —</p>
        <p>все достопримечательности находятся очень близко</p>
      </li>
      <li>
        <h3>Красивая дорога</h3>
        <p> — №4 —</p>
        <p>ехать в седону из лас-вегаса совсем не скучно!</p>
      </li>
      <li>
        <h3>Мало туристов</h3>
        <p> — №5 —</p>
        <p>большинство едет в гранд каньон и толпится там</p>
      </li>
    </ul>
  </section>

2021-06-23 13:37 UTC, Kirill-meta commented on index.html
> +    <ul>
так правильнее?

2021-06-28 10:38 UTC, mikhin commented on index.html
> +    <a href="#"> Поиск Гостиницы в седоне </a>
Да, тогда не нужно)

2021-06-29 11:31 UTC, mikhin approved these changes

2021-06-29 11:31 UTC, merged